version: "3.2"
services:
  postgres:
    image: postgres
    container_name: toroto_postgres
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=toroto_challenge.settings.development
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    tty: true
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start